server:
  port: 2019

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      
  datasource:
    platform: h2
    url: jdbc:h2:mem:usermgm-service;DB_CLOSE_DELAY=-1
    username: pratik
    password: pratik
    
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true